channels:
  - conda-forge
  - biobuilds
dependencies:
  - biopython
  - clustalw=2.1
  - codecov
  - cython
  - griddataformats
  - gsd
  - hypothesis
  - joblib>=0.12
  - matplotlib
  - mmtf-python
  - mock
  - netcdf4
  - networkx
  - numpy
  - parmed
  - pip
  - psutil
  - pytest
  - python=3.7
  - scikit-learn
  - scipy
  - seaborn>=0.7.0,<=0.9
  - six
  - sphinx=1.8.5
  - sphinx_rtd_theme
  - tqdm
  - pip:
      - sphinx_rtd_theme
      - sphinx-sitemap
